/*
 * $Copyright: (c) 2018 Broadcom Corp.
 * All Rights Reserved.$
 * File:     bm_enum.h
 * Purpose:  Behavior Model external structs
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated
 * Edits to this file will be lost when it is regenerated.
 *
 */

#ifndef _BM_ENUM_H_
#define _BM_ENUM_H_


typedef enum bm_sid_e {
    SOFTWARE_BLOCKMAP,
    SFC_EDB_PROFILEm = 1,
    SFC_IARB_PROFILEm = 2,
    SFC_MMU_PROFILEm = 3,
    ING_PKT_COUNTERm = 4,
    BCM_TBL_ENUM_COUNT = 5
} bm_sid_t;

#endif /* _BM_ENUM_H_ */

